### ISSUE TITLE
chips editor is not working 

### ISSUE THREAD

**Issue by NzeroN** [CensoredUsername/Nier-Automata-editor#6] opened 2017-09-13 11:29 UTC
i have tried to change some chip but when i saved and open chips editor again to check it nothing have happen , nothing have change

**Comment by CensoredUsername** [comment] 2017-10-31 15:52
I couldn't reproduce this, so closing for now unless a better description of the problem can be given.

**Closed as completed by CensoredUsername** 2017-10-31 15:52 UTC

**Comment by matanui159** [comment] 2018-06-03 11:56
I have the same issue with the editor. When I edit the chips, save, exit the program, enter again, the chips are reset back to what they were. Also to note: I have the NieR: Automata DLC installed
